package com.HetNagda.domain

// Domain models for the Claude LLM service API
case class ClaudeRequest(
                          inputText: String,                    // The input text to be processed by Claude
                          temperature: Option[Double] = None,    // Controls response randomness
                          maxTokens: Option[Int] = None         // Maximum tokens in generated response
                        )

case class RequestContext(
                           requestId: String                     // Unique identifier for request tracing
                         )

case class ApiGatewayRequest(
                              queryStringParameters: Map[String, String],  // Request query parameters
                              requestContext: RequestContext              // Request metadata context
                            )

case class ApiGatewayResponse(
                               statusCode: Int,                      // HTTP response status
                               headers: Map[String, String],         // Response headers
                               body: String                          // Response content
                             )

case class ClaudeResponse(
                           generatedText: String                 // Text generated by Claude
                         )

case class ErrorResponse(
                          errorMessage: String                  // Error description for failed requests
                        )